4 component header profile
nology-tech/ecf-cms pull request #12
Opened 2022-09-29 15:17 UTC by karinhawk

Tests pass for header profile and the profile is fully styled with variables and pictures.

2022-10-07 10:27 UTC, DorBia requested changes
Changes needed

2022-10-07 10:27 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +const HeaderProfile = () => {
Has to take props and not have hardcoded informations

2022-10-07 10:27 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +        <h2 className='header-profile__name'>Brett Zieme</h2>
Props needed

2022-10-07 10:27 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +        <p className='header-profile__role'>Admin</p>
Props needed

2022-10-07 10:27 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +import React from 'react'
Not needed

2022-10-07 10:27 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +import profilePicture from '../../assets/profile-picture.svg'
Profile picture can't be hardcoded

2022-10-07 11:19 UTC, meesha94 commented on src/components/HeaderProfile/HeaderProfile.scss
> +        margin-right: 8px;
change to rem

2022-10-07 15:38 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +      <img className="header-profile__image" src={profileImg} alt="profile picture"/>
Can you change alt to just "user avatar"?

2022-10-07 15:39 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.jsx
> +        <img src={Arrow} alt="toggle" />
Maybe change A to a?

2022-10-07 15:41 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.scss
> +* {
Can you get rid of this * part, it's done in main.scss, which is imported to App.jsx, so it will be everywhere

2022-10-07 15:45 UTC, DorBia commented on src/components/HeaderProfile/HeaderProfile.test.jsx
> +    !expect(svg).toBeInTheDocument();
const svgAltText = screen.queryByText("user avatar");  <- you want to just check if the text is displayed somewhere, not an alt text, as this one is looking for it in HTML, so it's always there
expect(svgAltText).toBeFalsy();

2022-10-07 23:34 UTC, DorBia approved these changes

2022-10-08 13:00 UTC, meesha94 approved these changes

2022-10-08 13:01 UTC, merged