58 searchbar component universal
nology-tech/ecf-cms pull request #14
Opened 2022-09-29 15:51 UTC by OmarKarame

2022-09-30 15:45 UTC, AdrianRotila requested changes
Searchbar tocamel case

2022-10-03 15:52 UTC, AdrianRotila requested changes

2022-10-03 15:52 UTC, AdrianRotila commented on src/components/SearchBar/SearchBar.jsx
> +const SearchBar = ({placeholderText, searchWord, handleSearchInput }) => {
placeholder to placeHolder

2022-10-03 15:52 UTC, AdrianRotila commented on src/components/SearchBar/SearchBar.scss
> +        //These will need to be changed to new variables
Please remove these comments

2022-10-03 15:52 UTC, AdrianRotila commented on src/components/SearchBar/SearchBar.jsx
> +      <input type="text" placeholder={placeholderText} value={searchWord} onChange={handleSearchInput} className="search-bar__input" data-testid="search-input"/>
data-testid?

2022-10-04 15:30 UTC, AdrianRotila approved these changes

2022-10-04 15:31 UTC, JosieAilsa approved these changes

2022-10-04 15:31 UTC, merged