20 button component universal
nology-tech/ecf-cms pull request #20
Opened 2022-10-03 14:59 UTC by A-M-98

2022-10-03 15:36 UTC, AdrianRotila requested changes

2022-10-03 15:36 UTC, AdrianRotila commented on src/components/Button/EveryButton.jsx
> +import React from 'react'
Please remove this file

2022-10-04 13:44 UTC, karinhawk commented
Deleted unecessary jsx file. All tests pass.

2022-10-04 15:11 UTC, AdrianRotila approved these changes

2022-10-04 15:16 UTC, AdrianRotila approved these changes

2022-10-04 15:17 UTC, merged