5 import all svgs figma
nology-tech/ecf-cms pull request #4
Opened 2022-09-27 15:52 UTC by OmarKarame

Added all the images and svg files for use.

2022-09-28 13:21 UTC, AdrianRotila requested changes
Hi guys, please make sure that you run a npm install and then push the changes

2022-09-28 13:56 UTC, JosieAilsa reviewed
- Make sure all icons are svgs 
- Where possible use SVG e.g. vector art

2022-09-28 14:13 UTC, JosieAilsa submitted a review, later dismissed

2022-09-28 14:32 UTC, AdrianRotila requested changes
src/assets/welcome-back-multi-phone-image-purple.jpg Could you please change this one to svg or png?

2022-09-29 14:26 UTC, JosieAilsa approved these changes

2022-09-29 14:26 UTC, merged