completed overview component with test
nology-tech/ecf-cms pull request #51
Opened 2022-10-10 15:50 UTC by OmarKarame

2022-10-10 20:36 UTC, DorBia requested changes

2022-10-10 20:36 UTC, DorBia commented on src/components/Overview/Overview.scss
> +
Please set max width

2022-10-10 20:36 UTC, DorBia commented on src/components/Overview/Overview.test.jsx
> +});
Add at least one more test to check if things render

2022-10-10 20:36 UTC, DorBia commented on src/components/Overview/Overview.jsx
> +import React from 'react'
This line is not needed

2022-10-12 14:48 UTC, karinhawk approved these changes

2022-10-12 14:48 UTC, BrookeVerse approved these changes

2022-10-12 14:49 UTC, merged