amended card to render categories menu
nology-tech/ecf-cms pull request #57
Opened 2022-10-12 13:57 UTC by AndyBowerman

amended card to render categories menu and added boolean condition prop to card container

2022-10-12 15:28 UTC, karinhawk commented on src/components/Card/Card.jsx
>        <img className="card__image" src={img} alt="Card Image" />
pass alt text as props for more specific description for screen readers please (line 23)

2022-10-12 15:33 UTC, karinhawk requested changes
please make changes requested

2022-10-13 14:50 UTC, BrookeVerse commented on src/components/Card/Card.jsx
>          <h2 className="card__title">{title}</h2>
Needs to be linkable

2022-10-14 13:43 UTC, karinhawk approved these changes

2022-10-14 13:48 UTC, BrookeVerse approved these changes

2022-10-14 13:48 UTC, merged