92 pathway overview display component
nology-tech/ecf-cms pull request #68
Opened 2022-10-17 13:14 UTC by meesha94

2022-10-17 14:43 UTC, BrookeVerse commented on src/components/PathwayDisplay/PathwayDisplay.jsx
> +          <img className="pathway-display__option" src ={hamburger} alt="list view option button" onClick={() => toggleDisplay(false)}/>
Can we change so that selected changes the border and opacity what is selected, as discussed :D

2022-10-17 14:44 UTC, BrookeVerse requested changes
Please make changes in comment.

2022-10-17 14:55 UTC, BrookeVerse requested changes
Just one other thing to change please

2022-10-19 13:11 UTC, karinhawk commented on src/components/PathwayDisplay/PathwayDisplay.scss
> +    justify-content: space-between;
comment

2022-10-19 13:11 UTC, karinhawk approved these changes

2022-10-19 13:12 UTC, karinhawk commented on src/App.jsx
>        <Route path="*" element={<Home />} />
comment

2022-10-20 14:47 UTC, OmarKarame approved these changes

2022-10-20 14:52 UTC, Connz17 approved these changes

2022-10-20 14:53 UTC, merged