116 pathway view options bug fix
nology-tech/ecf-cms pull request #74
Opened 2022-10-19 14:38 UTC by lucygilhooly

2022-10-20 14:11 UTC, OmarKarame commented on src/components/ViewOptions/ViewOptions.jsx
> -const ViewOptions = () => {
Line 4: Please pass in a function as a prop so we can change routes from container.

2022-10-20 14:17 UTC, OmarKarame requested changes
Check comments

2022-10-20 20:12 UTC, OmarKarame commented on src/pages/Home/Home.jsx
> +import ViewOptions from "../../components/ViewOptions/ViewOptions";
Please remove this import

2022-10-20 20:13 UTC, OmarKarame requested changes
Please check comments and don't forget to remove component rendering in layout

2022-10-21 09:56 UTC, OmarKarame approved these changes

2022-10-21 09:58 UTC, Connz17 approved these changes

2022-10-21 09:58 UTC, merged