109 page not found
nology-tech/ecf-cms pull request #75
Opened 2022-10-19 14:49 UTC by BrookeVerse

2022-10-19 14:58 UTC, OmarKarame commented on src/App.jsx
> -import Home from "./pages/Home/Home";
Line 2: Return the Home import.

2022-10-19 14:59 UTC, OmarKarame commented on src/App.jsx
> +import PageNotFound from "./components/PageNotFound/PageNotFound";
Line 3: Remove import

2022-10-19 14:59 UTC, OmarKarame commented on src/App.jsx
> -      <Route path="*" element={<Home />} />
Line 8: Return Route path for home (<Route path="*" element={<Home />} />)

2022-10-19 15:00 UTC, OmarKarame commented on src/App.jsx
> +      <Route path="*" element={< PageNotFound/>} />
Line 8: Remove Route

2022-10-19 15:02 UTC, OmarKarame commented on src/components/PageNotFound/PageNotFound.test.jsx
> +  it("Should render an button", () => {
Line 19: Change "an button" to "a button"

2022-10-19 15:03 UTC, OmarKarame requested changes
Please check comments and remember to return Home to its original state.

2022-10-19 15:12 UTC, BrookeVerse commented on src/App.jsx
> -import Home from "./pages/Home/Home";
Made Change

2022-10-19 15:13 UTC, BrookeVerse commented on src/App.jsx
> +import PageNotFound from "./components/PageNotFound/PageNotFound";
Made Change

2022-10-19 15:13 UTC, BrookeVerse commented on src/App.jsx
> +      <Route path="*" element={< PageNotFound/>} />
Made Change

2022-10-20 15:13 UTC, Connz17 approved these changes

2022-10-20 15:14 UTC, merged