103 checkbox input component
nology-tech/ecf-cms pull request #76
Opened 2022-10-19 15:18 UTC by meesha94

2022-10-20 13:52 UTC, OmarKarame commented on src/components/CheckboxInput/CheckboxInput.jsx
> +      <input type="text" className="checkbox__input" />
Line 6: Please add an onChange so a function can update info in container.

2022-10-20 13:53 UTC, OmarKarame commented on src/components/CheckboxInput/CheckboxInput.jsx
> +const CheckboxInput = () => {
Line 3: Please pass in props of functions to handle changes to the text input and checkbox input.

2022-10-20 13:55 UTC, OmarKarame requested changes
Please check the comments and add code appropriately. (Any questions please feel free to ask!)

2022-10-21 11:14 UTC, OmarKarame approved these changes

2022-10-21 11:21 UTC, Connz17 approved these changes

2022-10-21 11:21 UTC, merged