64 feature article list cards
nology-tech/ecf-cms pull request #8
Opened 2022-09-28 13:45 UTC by AndyBowerman

Created article card. Contains placeholder text and images to be replaced by state at a later date.
Styling applied based on figma design. Will need to be updated with the project variables once they are available.
Currently passing all tests written. Tested elements of the component appear on the users page.

2022-09-29 15:32 UTC, nologyRob commented on src/components/ArticleListCards/ArticleListCards.test.jsx
> +import ""
What's this?

2022-09-29 15:35 UTC, nologyRob commented on src/components/ArticleListCards/ArticleListCards.jsx
> +import React from 'react'
Rewrite the entire component with props in mind.

2022-09-29 18:46 UTC, nologyRob requested changes

2022-09-29 18:46 UTC, nologyRob commented on src/components/ArticleListCards/ArticleListCards.scss
> +
Sorry but remove extra line

2022-09-29 18:46 UTC, nologyRob commented on src/components/ArticleListCards/ArticleListCards.scss
> +
Sorry but remove extra line

2022-10-03 15:28 UTC, AdrianRotila requested changes

2022-10-03 15:38 UTC, closed without merging