102 questions and answers container
nology-tech/ecf-cms pull request #80
Opened 2022-10-20 14:45 UTC by atif298

Handlers are being passed down for larger containers to build functions for retrieving index and editing and deletion. 
Tests all passed.
Styling according to Figma.

2022-10-20 15:27 UTC, Connz17 submitted a review, later dismissed

2022-10-21 10:04 UTC, OmarKarame requested changes
Please remove AddQuestion component from this branch as it has been already merged from another branch

2022-10-21 15:33 UTC, Connz17 approved these changes

2022-10-21 15:33 UTC, OmarKarame approved these changes

2022-10-21 15:33 UTC, merged